import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

import Game from "../components/game/main/game";
import Menu from "../components/menu/main/menu";
import styles from "../styles/Home.module.scss";
const Home: NextPage = () => {
  const [Play, setPlay] = useState(false);
  const playGame = () => {
    setPlay(true);
  };

  return (
    <div>
      <Head>
        <title>snake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {Play ? (
          <div>
            <Game />
          </div>
        ) : (
          <div>
            <Menu handelPlay={playGame} />
          </div>
        )}
      </div>
    </div>
  );
};

export default Home;
